### ISSUE TITLE
20230223 review

### ISSUE THREAD

**Issue by init** [zeronethunter/technopark-highload-course#2]
не хватает:
1. навигации по товарам (каталог/поиск)
2. склады и логистика
3. функционал для продавцов (пока не заявлен но это стандартный функционал маркетплейсов)

**Comment by zeronethunter** [comment]
Добрый вечер, писал вам в вк, но вы не ответили, пробую здесь)
MVP по проекту уточнил, добавил пункты выше ⬆️
